### ISSUE TITLE
Invalid version of beats protocol: 34

### ISSUE THREAD

**Issue by sunojvijayan** [Aigent/log4js-logstash-tcp#4]
My configuration is

`var log4js = require('log4js');
// var elkConfig = Object.assign({}, require('config').get('elk'));
log4js.configure({
    appenders: {
        console: {
            type: 'console'
        },
        logstash: {
            host: "localhost",
            port: 5044,
            type: "log4js-logstash-tcp",
            logType: 'mm', // Optional, defaults to 'category'
            fields: {             // Optional, will be added to the 'fields' object in logstash
                type: 'mm-logs',
                field2: 'value2'
            }
        }
    },
    categories: {
        default: { appenders: ['logstash'], level: 'trace' }
    }
});
var log = log4js.getLogger();
module.exports.log = log;`

When i try to send log i get this error in logstash logs.

[2021-01-30T08:28:41,894][INFO ][org.logstash.beats.BeatsHandler] [local: 127.0.0.1:5044, remote: 127.0.0.1:49092] Handling exception: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 34
[2021-01-30T08:28:41,895][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 34
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:405) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:372) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$300(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext$4.run(AbstractChannelHandlerContext.java:236) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 34
        at org.logstash.beats.Protocol.version(Protocol.java:22) ~[logstash-input-beats-5.1.9.jar:?]
        at org.logstash.beats.BeatsParser.decode(BeatsParser.java:62) ~[logstash-input-beats-5.1.9.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        ... 10 more

**Comment by degola** [comment]
How does your logstash configuration look like for the input?
This log4js plugin requires the logstash type `tcp-input`:
```
input {
	tcp {
		codec => "json"
		port => 5050
		type => "tcp-input"
	}
}
```
It seems that you try to push the data to a beats logstash input which is, as expected, not going to work.

**Comment by sunojvijayan** [comment]
Extremely sorry. That was the issue . I was using beats instead of tcp. Thanks for your swift help.
